exclude: "pkgs/fc/sensusyntax/fixtures/(syntaxerror|empty).json|(tests/testlib.nix|nixos/roles/devhost/vm.nix|tests/physical-installer.nix)|^changelog.d/new_fragment.md.j2$|tests/.+\\.py"
repos:
- repo: local
  hooks:
    - id: nixfmt
      name: nixfmt
      entry: nixfmt
      language: system
      files: \.nix$
- repo: https://github.com/google/keep-sorted
  rev: v0.9.1
  hooks:
    - id: keep-sorted
