exclude: "pkgs/fc/sensusyntax/fixtures/(syntaxerror|empty).json|(tests/testlib.nix|nixos/roles/devhost/vm.nix|tests/physical-installer.nix)"
repos:
- hooks:
  - id: nixfmt
  repo: https://github.com/NixOS/nixfmt
  rev: a4639036723e510d8331124c80d9ca14dd7aba02
