exclude: "pkgs/fc/sensusyntax/fixtures/(syntaxerror|empty).json|(tests/testlib.nix|nixos/roles/devhost/vm.nix)|^changelog.d/new_fragment.md.j2$|tests/.+\\.py"
repos:
- repo: local
  hooks:
    - id: nixfmt
      name: nixfmt
      entry: nixfmt
      language: system
      files: \.nix$
