exclude: ^secrets/|^appenv$|pkgs/fc/sensusyntax/fixtures/(syntaxerror|empty).json|(tests/testlib.nix|nixos/roles/devhost/vm.nix|tests/physical-installer.nix)|^changelog.d/new_fragment.md.j2$|tests/.+\.py
repos:
- hooks:
  - id: detect-private-key
  - id: check-added-large-files
  - exclude: "(?x)^(\n  secrets/|environments/.*/secret.*|\n  .*\\.patch\n)$\n"
    id: trailing-whitespace
  - exclude: "(?x)^(\n  environments/.*/secret.*|\n  .*\\.patch\n)$\n"
    id: end-of-file-fixer
  - exclude: "(?x)^(\n  environments/.*/secret.*|\n  .*\\.patch\n)$\n"
    id: check-yaml
  - exclude: "(?x)^(\n  environments/.*/secret.*|\n  .*\\.patch\n)$\n"
    id: check-json
  - exclude: "(?x)^(\n  environments/.*/secret.*|\n  .*\\.patch\n)$\n"
    id: check-xml
  - exclude: "(?x)^(\n  environments/.*/secret.*|\n  .*\\.patch\n)$\n"
    id: check-toml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  # Run the linter.
    - id: ruff-check
      args: [ "--select", "I", "--fix" ]
    # Run the formatter.
    - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.9
- hooks:
  - entry: nixfmt
    files: \.nix$
    id: nixfmt
    language: system
    name: nixfmt
  repo: local
- repo: https://github.com/google/keep-sorted
  rev: v0.9.1
  hooks:
    - id: keep-sorted
