#!/usr/bin/env bash
# Usage: eval `./dev-setup`
set -e
base=$PWD
if [[ -z "$NIX_PATH" ]]; then
    nixpkgsBootstrap=$(realpath $HOME/.nix-defexpr/channels_root/nixpkgs)
    if [[ -z nixpkgsBootstrap ]]; then
        echo "$0: need <nixpkgs> available in system channels" >&2
        exit 1
    fi
    export NIX_PATH="nixpkgs=$nixpkgsBootstrap"
fi
channels=`nix-build -Q nixpkgs.nix -A allUpstreams --no-out-link`
if [[ -z $channels ]]; then
    echo "$0: failed to build nixpkgs+overlay" >&2
    exit 1
fi
mkdir -p channels
find $channels -maxdepth 1 -type l | while read channel; do
    ln -fs $channel channels/
done
if ! [[ -e channels/fc ]]; then
    ln -s .. channels/fc
fi
echo "export NIX_PATH=$base/channels:fc=$base:nixos-config=$base/nixos/platform"
