#!/usr/bin/env python3
"""Check ADR numbering and regenerate adr/README.md.

Fails if two ADRs share a number or if an ADR's heading number does not
match its file name. The generated index lists one ADR per line, so two
branches that add ADRs concurrently will touch the same lines and cause a
merge conflict instead of silently merging duplicate numbers.
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

ADR_DIR = Path(__file__).parent
INDEX = ADR_DIR / "README.md"
FILENAME = re.compile(r"^(\d{4})-.+\.md$")
HEADING = re.compile(r"^#\s+ADR\s+(\d+)\s+-\s+(.+?)\s*$")
STATUS = re.compile(r"^Status:\s*(.+?)\s*$", re.MULTILINE)

HEADER = """\
# Architecture Decision Records

<!-- Generated by adr/update-index.py (pre-commit hook adr-index). Do not edit.
     If this file conflicts during a merge or rebase, someone else added an
     ADR in parallel: renumber yours if needed and re-run the script. -->

| Number | Status | Title |
|-------:|--------|-------|
"""


def main():
    errors: list[str] = []
    by_number = defaultdict[int, list[tuple[str, str, str]]](list)
    for path in sorted(ADR_DIR.glob("*.md")):
        m = FILENAME.match(path.name)
        if not m:
            continue
        number = int(m.group(1))
        text = path.read_text()
        first_line = text.split("\n", 1)[0]
        h = HEADING.match(first_line)
        if not h:
            errors.append(
                f"{path}: first line must look like '# ADR {number} - Title'"
            )
            continue
        if int(h.group(1)) != number:
            errors.append(
                f"{path}: heading number {h.group(1)} does not match file name"
            )
        s = STATUS.search(text)
        if not s:
            errors.append(f"{path}: missing 'Status: ...' line")
            continue
        by_number[number].append((path.name, h.group(2), s.group(1)))

    for number, adrs in sorted(by_number.items()):
        if len(adrs) > 1:
            names = ", ".join(adr[0] for adr in adrs)
            errors.append(f"duplicate ADR number {number}: {names}")

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    rows = [
        f"| {number} | {status} | [{title}]({name}) |"
        for number, [(name, title, status)] in sorted(by_number.items())
    ]
    content = HEADER + "\n".join(rows) + "\n"
    if INDEX.exists() and INDEX.read_text() == content:
        return 0
    _ = INDEX.write_text(content)
    print(f"Updated {INDEX}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
