vrrp_script check_dev_route_v4 {
      script "/etc/keepalived/check-default-route-v4 '172.20.0.0/16 via'"
      interval 1
      fall 2
      rise 2
}

vrrp_script check_dev_route_v6 {
      script "/etc/keepalived/check-default-route-v6 '2a06:3a80:300::/40 via'"
      interval 1
      fall 2
      rise 2
}

vrrp_script check_zebra_liveness {
      script "/etc/keepalived/check-zebra-liveness"
      interval 1
      fall 2
      rise 2
}

track_file check_stop_file {
  # Allow admins to locally send keepalive into FAIL state by adding
  # a non "0" entry
  file /etc/keepalived/stop
  # 0 as default causes FAIL if anything != 0 is in the file
  weight 0
  init_file 0
}

track_file check_maint_file {
  # Used by fc-keepalived enter-maintenance
  file /etc/keepalived/fcio_maintenance
  weight -20
  init_file 0
}

vrrp_sync_group router {
    group { mgm fe srv video access }

    notify_master "/etc/keepalived/fc-keepalived notify master"
    notify_backup "/etc/keepalived/fc-keepalived notify backup"
    notify_fault "/etc/keepalived/fc-keepalived notify fault"
    notify_stop "/etc/keepalived/fc-keepalived notify stop"

    track_script {
        check_dev_route_v4 weight 10
        check_dev_route_v6 weight 5
        check_zebra_liveness
    }

    track_file {
      check_stop_file
      check_maint_file
    }
}

vrrp_instance mgm {
    interface ethmgm
    state BACKUP
    virtual_router_id 51
    priority 100
    advert_int 1
    garp_master_refresh 30

    virtual_ipaddress {
        2a06:3a80:0:1::1/64
    }
    virtual_ipaddress_excluded {
        172.16.1.1/24
    }
}

vrrp_instance fe {
    interface brfe
    state BACKUP
    virtual_router_id 51
    priority 100
    advert_int 1
    garp_master_refresh 30

    virtual_ipaddress {
        2a06:3a80:0:2::1/64
    }
    virtual_ipaddress_excluded {
        185.105.255.1/25
    }
}

vrrp_instance srv {
    interface brsrv
    state BACKUP
    virtual_router_id 51
    priority 100
    advert_int 1
    garp_master_refresh 30

    virtual_ipaddress {
        2a06:3a80:0:3::1/64
    }
    virtual_ipaddress_excluded {
        172.16.48.1/20
    }
}

vrrp_instance video {
    interface ethvideo
    state BACKUP
    virtual_router_id 51
    priority 100
    advert_int 1
    garp_master_refresh 30
    dont_track_primary

    virtual_ipaddress {
        2a06:3a80:0:23::1/64
    }
    virtual_ipaddress_excluded {
        172.17.112.1/20
    }
}

vrrp_instance access {
    interface ethaccess
    state BACKUP
    virtual_router_id 51
    priority 100
    advert_int 1
    garp_master_refresh 30

    virtual_ipaddress {
        2a06:3a80:0:41::1/64
    }
    virtual_ipaddress_excluded {
        172.18.144.1/20
        185.105.255.193/27
    }
}
