# This file is auto-generated by airgapped-k3s-images.py
# Do not edit this file, edit and re-run airgapped-k3s-images.py instead
[
{
  imageName = "docker.io/rancher/klipper-helm";
  imageDigest = "sha256:87db3ad354905e6d31e420476467aefcd8f37d071a8f1c8a904f4743162ae546";
  sha256 = "03qilngaxzv4l0yb7cvvfhb32ll3ajx5lrf53ma186dv6xzwl2ph";
  finalImageName = "docker.io/rancher/klipper-helm";
  finalImageTag = "v0.8.3-build20240228";
}
{
  imageName = "docker.io/rancher/klipper-lb";
  imageDigest = "sha256:558dcf96bf0800d9977ef46dca18411752618cd9dd06daeb99460c0a301d0a60";
  sha256 = "1lqayby3yj7ivcr7v9awrcz9wfv2r5b3bd3k2q89gwkc2ivnyagp";
  finalImageName = "docker.io/rancher/klipper-lb";
  finalImageTag = "v0.4.7";
}
{
  imageName = "docker.io/rancher/local-path-provisioner";
  imageDigest = "sha256:aee53cadc62bd023911e7f077877d047c5b3c269f9bba25724d558654f43cea0";
  sha256 = "15vvqqf3s8kpv8drdvaykyqadcss90b8kxwbl9ifiq5qvgkxza4v";
  finalImageName = "docker.io/rancher/local-path-provisioner";
  finalImageTag = "v0.0.26";
}
{
  imageName = "docker.io/rancher/mirrored-coredns-coredns";
  imageDigest = "sha256:a11fafae1f8037cbbd66c5afa40ba2423936b72b4fd50a7034a7e8b955163594";
  sha256 = "04a3nn5pvpd97b52nq08q0axx8bbmgcj9f8779d062yan55afx5r";
  finalImageName = "docker.io/rancher/mirrored-coredns-coredns";
  finalImageTag = "1.10.1";
}
{
  imageName = "docker.io/rancher/mirrored-library-busybox";
  imageDigest = "sha256:f9bd56486743d20ed2c148cdef23fd2e9c3e9dc1377df303e777dad288e0e17d";
  sha256 = "185m58pqc0j39yvjilwa9jcpgzapg9dynqi5xv08vr6sf53rm8mn";
  finalImageName = "docker.io/rancher/mirrored-library-busybox";
  finalImageTag = "1.36.1";
}
{
  imageName = "docker.io/rancher/mirrored-library-traefik";
  imageDigest = "sha256:606c4c924d9edd6d028a010c8f173dceb34046ed64fabdbce9ff29b2cf2b3042";
  sha256 = "1r4kmk9wn84b9s89a4gc5anys9hnrjjlzcj0b3cv6mimlc7al9n6";
  finalImageName = "docker.io/rancher/mirrored-library-traefik";
  finalImageTag = "2.10.7";
}
{
  imageName = "docker.io/rancher/mirrored-metrics-server";
  imageDigest = "sha256:20b8b36f8cac9e25aa2a0ff35147b13643bfec603e7e7480886632330a3bbc59";
  sha256 = "1ykkhx85q0556in6nvncikrhnxwgs5msf4vjxns9qk74dqrvchxb";
  finalImageName = "docker.io/rancher/mirrored-metrics-server";
  finalImageTag = "v0.7.0";
}
{
  imageName = "docker.io/rancher/mirrored-pause";
  imageDigest = "sha256:74c4244427b7312c5b901fe0f67cbc53683d06f4f24c6faee65d4182bf0fa893";
  sha256 = "0qm3q199bzj5z73fs2h6ivkbmqcifgjbb34i145chmx5hrg8zfr1";
  finalImageName = "docker.io/rancher/mirrored-pause";
  finalImageTag = "3.6";
}
]
