# This file is auto-generated by airgapped-k3s-images.py
# Do not edit this file, edit and re-run airgapped-k3s-images.py instead
[
{
  imageName = "docker.io/rancher/klipper-helm";
  imageDigest = "sha256:f9c16f95df8286e4fea249fcc01290d0c1e01139976b3d1f75a699037715e1d9";
  sha256 = "1xbfv809w182y1in6isghmyfr1rp6cvlqqhm23dmp1incc4dbl1z";
  finalImageName = "docker.io/rancher/klipper-helm";
  finalImageTag = "v0.9.2-build20240828";
}
{
  imageName = "docker.io/rancher/klipper-lb";
  imageDigest = "sha256:dd380f5d89a52f2a07853ff17a6048f805c1f8113b50578f3efc3efb9bcf670a";
  sha256 = "1dc7hs269jazjhvnz94zlp91a32z4c79ykvyw1ab8k4lqf5jjh4n";
  finalImageName = "docker.io/rancher/klipper-lb";
  finalImageTag = "v0.4.9";
}
{
  imageName = "docker.io/rancher/local-path-provisioner";
  imageDigest = "sha256:f77fa34dd9d000daf6fd6029bf05de6b351b4fe4287cbc0ad2abb11a91df2ced";
  sha256 = "0zgdg8a1bm81n7r7iw6g10j47v5riixl9xmgnspy71n4gkrdkxrj";
  finalImageName = "docker.io/rancher/local-path-provisioner";
  finalImageTag = "v0.0.28";
}
{
  imageName = "docker.io/rancher/mirrored-coredns-coredns";
  imageDigest = "sha256:8461f69c1d8252a73f4c217ca17c75ac704af1c54c2332c199c637ab2815536a";
  sha256 = "1cqvhpcwc7v2m18kwvdq5954qnx1nr1jvly4086cr3b4mkqs6117";
  finalImageName = "docker.io/rancher/mirrored-coredns-coredns";
  finalImageTag = "1.11.3";
}
{
  imageName = "docker.io/rancher/mirrored-library-busybox";
  imageDigest = "sha256:14053fb060c76cf49ba3a16e50573db835c8e7282cf394fe3409bc7035e8c63f";
  sha256 = "11kvx6qy0kpdlzw67h0xdrjvvh4xq7w7rhby8hc64qwrlvnd6870";
  finalImageName = "docker.io/rancher/mirrored-library-busybox";
  finalImageTag = "1.36.1";
}
{
  imageName = "docker.io/rancher/mirrored-library-traefik";
  imageDigest = "sha256:13339ae4229b7148e12460f4cbabc64019a18dd0645f3a2518a8b1e0a938aa38";
  sha256 = "123c439aa4q1wdbna8a98fmd8ywl32mcm81gz13pybivx3d8v1g2";
  finalImageName = "docker.io/rancher/mirrored-library-traefik";
  finalImageTag = "2.11.8";
}
{
  imageName = "docker.io/rancher/mirrored-metrics-server";
  imageDigest = "sha256:dccf8474fb910fef261d31d9483d7e4c1df7b86cf4d638fb6a7d7c88bd51600a";
  sha256 = "0q74is7dhibwhs4lp67bk2svbcrbmvv8ln0ssjff0dpfhb6ysj36";
  finalImageName = "docker.io/rancher/mirrored-metrics-server";
  finalImageTag = "v0.7.2";
}
{
  imageName = "docker.io/rancher/mirrored-pause";
  imageDigest = "sha256:74c4244427b7312c5b901fe0f67cbc53683d06f4f24c6faee65d4182bf0fa893";
  sha256 = "0qm3q199bzj5z73fs2h6ivkbmqcifgjbb34i145chmx5hrg8zfr1";
  finalImageName = "docker.io/rancher/mirrored-pause";
  finalImageTag = "3.6";
}
]
