# This file is auto-generated by airgapped-k3s-images.py
# Do not edit this file, edit and re-run airgapped-k3s-images.py instead
[
  {
    imageName = "docker.io/rancher/klipper-helm";
    imageDigest = "sha256:251a6a3983934f1026c34f4337fc5a87e093a142438c7d16f7b31c179162176e";
    hash = "sha256-73LrDUTjjlIWj3CAPMY184Rmb/8V/HzlbejEa5b9HKw=";
    finalImageName = "docker.io/rancher/klipper-helm";
    finalImageTag = "v0.9.10-build20251111";
  }
  {
    imageName = "docker.io/rancher/klipper-lb";
    imageDigest = "sha256:7eb86d5b908ec6ddd9796253d8cc2f43df99420fc8b8a18452a94dc56f86aca0";
    hash = "sha256-0qedwbZR7D1GHZKOHksf99hiCdK+95UjGiViJoqYpnU=";
    finalImageName = "docker.io/rancher/klipper-lb";
    finalImageTag = "v0.4.13";
  }
  {
    imageName = "docker.io/rancher/local-path-provisioner";
    imageDigest = "sha256:9289da488b07912cb4128eb96928a331a5f3e60c28c5cfc5790f354a4ad0cc68";
    hash = "sha256-dRczkX+UmwSaKND50M9xuUSG9bi5G6R/w7ZEAqLYw/0=";
    finalImageName = "docker.io/rancher/local-path-provisioner";
    finalImageTag = "v0.0.32";
  }
  {
    imageName = "docker.io/rancher/mirrored-coredns-coredns";
    imageDigest = "sha256:9b9128672209474da07c91439bf15ed704ae05ad918dd6454e5b6ae14e35fee6";
    hash = "sha256-ZZIGTFi0bKgrWNc0SbiFCi+0pammSHxe9mzuRYAlB4U=";
    finalImageName = "docker.io/rancher/mirrored-coredns-coredns";
    finalImageTag = "1.13.1";
  }
  {
    imageName = "docker.io/rancher/mirrored-library-busybox";
    imageDigest = "sha256:8a45424ddf949bbe9bb3231b05f9032a45da5cd036eb4867b511b00734756d6f";
    hash = "sha256-oOghn/A6kwWhpXRaAjnW/ZhIlyCa0QqWJTCgm5sUcoQ=";
    finalImageName = "docker.io/rancher/mirrored-library-busybox";
    finalImageTag = "1.36.1";
  }
  {
    imageName = "docker.io/rancher/mirrored-library-traefik";
    imageDigest = "sha256:c56901603318ee375477ee5c3f50d175d3ec42dc102efc2f1158f0756ba4dffa";
    hash = "sha256-03dNEZ7OH3Hc/lBDHokyV2aVDF1/Y+Qy7ZefvCyf8t4=";
    finalImageName = "docker.io/rancher/mirrored-library-traefik";
    finalImageTag = "3.5.1";
  }
  {
    imageName = "docker.io/rancher/mirrored-metrics-server";
    imageDigest = "sha256:89258156d0e9af60403eafd44da9676fd66f600c7934d468ccc17e42b199aee2";
    hash = "sha256-TfprpvRZ+3ks9RsjqMVAsxNjdTz0FfwfwOmujwXXZGs=";
    finalImageName = "docker.io/rancher/mirrored-metrics-server";
    finalImageTag = "v0.8.0";
  }
  {
    imageName = "docker.io/rancher/mirrored-pause";
    imageDigest = "sha256:74c4244427b7312c5b901fe0f67cbc53683d06f4f24c6faee65d4182bf0fa893";
    hash = "sha256-IbuPXoalV8gKCZGMteRzkeG65o4GCu3G+UX+lVLAo2I=";
    finalImageName = "docker.io/rancher/mirrored-pause";
    finalImageTag = "3.6";
  }
]
