{ config, lib, pkgs, ... }:

with builtins;

let
  fclib = config.fclib;

  # Kubernetes services depend on autogenerated certs.
  # Certmgr needs some seconds to generate them if they don't exist.
  # We have to wait for the certs or the services will fail.
  mkUnitWaitForCerts = name: certNames:
    lib.nameValuePair "${name}"
      {
        preStart = let
          secretsPath = config.services.kubernetes.secretsPath;
          certConditions = map (n: "! -f ${secretsPath}/${n}.pem") certNames;
        in ''
          echo Waiting for required certs: ${lib.concatStringsSep ", " certNames}...
          while [[ ${lib.concatStringsSep " || " certConditions } ]]
          do
            sleep 1
          done
        '';
      };

  kubernetesModulesFromHere = [
    "services/security/certmgr.nix"
    "services/cluster/kubernetes/pki.nix"
    "services/networking/flannel.nix"
  ];

  master = fclib.findOneService "kubernetes-master-master";
in {

  disabledModules = kubernetesModulesFromHere;

  imports = [
    ./certmgr.nix
    ./frontend.nix
    ./master.nix
    ./node.nix
    ./pki.nix
    ./flannel.nix
  ];

  options = with lib; {
    flyingcircus.kubernetes.lib = mkOption {
      description = "Common code for our kubernetes modules.";
      type = types.attrs;
    };
  };

  config = lib.mkMerge [

    (lib.mkIf config.services.flannel.enable {
      services.flannel = {
        iface = "ethsrv";
        backend = { Type = "vxlan"; DirectRouting = true; };
        verbosity = 4;
      };
    })

    (lib.mkIf config.services.kubernetes.kubelet.enable {
      # Kubelet doesn't start with swap by default but we want to use swap.
      services.kubernetes.kubelet = {
        extraOpts = lib.mkForce "--fail-swap-on=false";
        clusterDns = head master.ips;
      };
    })

    (lib.mkIf config.services.kubernetes.proxy.enable {
      services.kubernetes.proxy = {
        # Works without proper hostname but avoids the error in kube-proxy log
        extraOpts = "--hostname-override=${config.networking.hostName}.fcio.net";
        # I don't really know what this bind address is for (has no visible effect)
        # but limiting it to srv is better than the default 0.0.0.0 default.
        bindAddress = head (fclib.listenAddresses "ethsrv");
      };
    })

    {
      flyingcircus.kubernetes.lib = { inherit mkUnitWaitForCerts; };

      systemd.services.kube-certmgr-bootstrap.preStart = ''
        mkdir -p ${config.services.kubernetes.secretsPath}
      '';

    }
  ];

}
