import syslog

import pytest

try:
    from systemd import journal
except ImportError:
    journal = None

from fc.util.logging import (
    JournalLogger,
    JournalLoggerFactory,
    SystemdJournalRenderer,
    _install_stamina_retry_hook,
    redact_stamina_retry_args,
)



def test_redact_stamina_retry_args_selectively_censors():
    args = (
        {
            "aareal:fc-loki": {
                "display_name": "Autogenerated by role loki",
                "access_key": "AKIAIOSFODNN7EXAMPLE",
                "secret_key": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
                "location": "rzob",
            },
        },
    )
    kwargs = {"token": "super-secret"}
    event_dict = {
        "event": "stamina.retry_scheduled",
        "args": args,
        "kwargs": kwargs,
        "attempt": 1,
        "callable": "fc.util.directory.DirectoryAPI.update_s3_users",
    }

    out = redact_stamina_retry_args(None, None, event_dict)

    user = out["args"][0]["aareal:fc-loki"]
    # Non-sensitive data is kept for debuggability...
    assert user["display_name"] == "Autogenerated by role loki"
    assert user["location"] == "rzob"
    # ...only credential-like values are redacted.
    assert user["secret_key"] == "[REDACTED]"
    assert user["access_key"] == "[REDACTED]"
    assert out["kwargs"]["token"] == "[REDACTED]"
    assert "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" not in str(out)


def test_redact_stamina_retry_args_keeps_other_events():
    event_dict = {"event": "user.sync_started", "count": 10}

    out = redact_stamina_retry_args(None, None, event_dict)

    assert out == {"event": "user.sync_started", "count": 10}


def test_install_stamina_retry_hook_registers_hook():
    from stamina import instrumentation

    _install_stamina_retry_hook()
    hooks = instrumentation.get_on_retry_hooks()

    assert len(hooks) == 1
    assert callable(hooks[0])

@pytest.mark.skipif(journal is None, reason="systemd package not available")
def test_journal_logger():
    factory = JournalLoggerFactory()
    logger = factory()
    assert isinstance(logger, JournalLogger)


@pytest.fixture
def journald_renderer():
    return SystemdJournalRenderer("test")


def test_journal_renderer(journald_renderer):
    event_dict = {
        "event": "test-event",
        "pid": 123,
        "timestamp": 1000000,
        "code_lineno": 2,
        "code_file": "file",
        "code_func": "func",
        "output": "output",
        "code_module": "module",
        "bool_var": True,
        "level": "debug",
        "none": None,
        "emptystring": "",
        "a_list": ["a", "b"],
        "a_tuple": ("a", "b"),
        "a_dict": dict(a=1, b=2),
        "multiline": "multi\nline",
    }

    message = (
        "test-event: a_dict={'a': 1, 'b': 2} a_list=['a', 'b'] a_tuple=('a', 'b') "
        + "bool_var=True emptystring='' multiline='multi\\nline' none=None"
    )

    expected_journal_msg = {
        "SYSLOG_IDENTIFIER": "test",
        "SYSLOG_FACILITY": syslog.LOG_LOCAL0,
        "EVENT": "test-event",
        "CODE_LINE": 2,
        "CODE_FILE": "file",
        "CODE_FUNC": "func",
        "OUTPUT": "output",
        "CODE_MODULE": "module",
        "EMPTYSTRING": "",
        "LEVEL": "debug",
        "MESSAGE": message,
        "PRIORITY": syslog.LOG_DEBUG,
        "A_DICT": '{"a": 1, "b": 2}',
        "A_TUPLE": '["a", "b"]',
        "A_LIST": '["a", "b"]',
        "NONE": "null",
        "BOOL_VAR": "true",
        "MULTILINE": "multi\nline",
    }

    rendered = journald_renderer(None, None, event_dict)
    assert "journal" in rendered
    assert rendered["journal"] == expected_journal_msg


def test_journal_renderer_replace_msg(journald_renderer):
    event_dict = {
        "event": "test-event",
        "pid": 123,
        "_replace_msg": "test msg with pid {pid}",
    }

    rendered = journald_renderer(None, None, event_dict)
    assert "journal" in rendered
    assert (
        rendered["journal"]["MESSAGE"] == "test-event: test msg with pid 123"
    )
