protocol static local_routerlab_4 {
  ipv4 {
    table master4;
  };

  route 172.21.82.0/24 unreachable;
  route 172.21.83.0/24 unreachable;
}

protocol static local_routerlab_6 {
  ipv6 {
    table master6;
  };

  route 2a06:3a80:300:100::/56 unreachable;
}

protocol device {
  scan time 60;
}

protocol bfd {
  strict bind on;
  interface "ethtr2";
}

protocol kernel kernel_4 {
  ipv4 {
    table master4;
    export all;
    import none;
  };

  metric 500;
  merge paths on;
}

protocol kernel kernel_6 {
  ipv6 {
    table master6;
    export all;
    import none;
  };

  metric 500;
  merge paths on;
}

filter net_routerlab_4 {
  if net ~ [ 172.21.82.0/24, 172.21.83.0/24 ] then {
    bgp_med = UPLINK_MED;
    accept;
  } else reject;
}

filter net_routerlab_6 {
  if net ~ [ 2a06:3a80:0300:100::/56+ ] then {
    bgp_med = UPLINK_MED;
    accept;
  } else reject;
}

filter default_route_4 {
  if net = 0.0.0.0/0 then accept; else reject;
}

filter default_route_6 {
  if net = ::/0 then accept; else reject;
}

template bgp peer_dev {
  local as 64515;
  neighbor as 64512;

  bfd;
  connect retry time 15;
  error wait time 5,10;
}

template bgp peer_dev_4 from peer_dev {
  ipv4 {
    table master4;
    import filter default_route_4;
    export filter net_routerlab_4;
  };
}

template bgp peer_dev_6 from peer_dev {
  ipv6 {
    table master6;
    import filter default_route_6;
    export filter net_routerlab_6;
  };
}

protocol bgp peer_dev_kenny04_4 from peer_dev_4 {
  neighbor 172.21.85.34;
}

protocol bgp peer_dev_kenny04_6 from peer_dev_6 {
  neighbor 2a06:3a80:300:10e::2;
}

protocol bgp peer_dev_kenny10_4 from peer_dev_4 {
  neighbor 172.21.85.35;
}

protocol bgp peer_dev_kenny10_6 from peer_dev_6 {
  neighbor 2a06:3a80:300:10e::3;
}
