# host config must include: PEER_IPV4, PEER_IPV6

protocol static local_whq_4 {
  ipv4 {
    table master4;
  };

  route 185.105.255.0/25 unreachable;
  route 185.105.255.160/27 unreachable;
  route 185.105.255.192/27 unreachable;
}

protocol static local_whq_6 {
  ipv6 {
    table master6;
  };

  route 2a06:3a80::/40 unreachable;
}


protocol device {
  scan time 60;
}

# bfd config in host-specific config in this location because the
# parser does not allow using defines for interface names.
#
# protocol bfd {
#   strict bind on;
#   interface ...;
# }

function net_whq_4() -> bool {
  if net ~ [ 185.105.255.0/25+, 185.105.255.160/27+, 185.105.255.192/27+ ] then {
    return true;
  } else return false;
}

function net_whq_6() -> bool {
  if net ~ [ 2a06:3a80::/40+ ] then {
    return true;
  } else return false;
}

function net_dev_4() -> bool {
  if net ~ [ 172.20.0.0/16+, 172.30.0.0/16+ ] then {
    return true;
  } else return false;
}

function net_dev_6() -> bool {
  if net ~ [ 2a06:3a80:0300::/40+ ] then {
    return true;
  } else return false;
}

filter default_route_4 {
  if net = 0.0.0.0/0 then accept; else reject;
}

filter default_route_6 {
  if net = ::/0 then accept; else reject;
}

protocol kernel kernel_4 {
  ipv4 {
    table master4;
    export all;
    import none;
  };

  metric 500;
  merge paths on;
}

protocol kernel kernel_6 {
  ipv6 {
    table master6;
    export all;
    import none;
  };

  metric 500;
  merge paths on;
}

template bgp peer_saltlabs {
  local as 64513;
  neighbor as 64514;

  bfd;
  connect retry time 15;
  error wait time 5,10;
}

template bgp peer_saltlabs_v4 from peer_saltlabs {
  ipv4 {
    table master4;
    import filter default_route_4;

    export filter {
      if net_whq_4() then {  # private dev networks not exported
        bgp_med = UPLINK_MED;
        accept;
      }
      reject;
    };

    import keep filtered on;
  };
}

template bgp peer_saltlabs_v6 from peer_saltlabs {
  ipv6 {
    table master6;
    import filter default_route_6;

    export filter {
      if net_whq_6() || net_dev_6() then {
        bgp_med = UPLINK_MED;
        accept;
      }
      reject;
    };

    import keep filtered on;
  };
}

protocol bgp peer_saltlabs_01_v4 from peer_saltlabs_v4 {
  neighbor PEER_IPV4;
}

protocol bgp peer_saltlabs_01_v6 from peer_saltlabs_v6 {
  neighbor PEER_IPV6;
}


template bgp peer_dev {
  local as 64513;

  passive;

  bfd;
  connect retry time 15;
  error wait time 5,10;
}

template bgp peer_dev_4 from peer_dev {
  ipv4 {
    table master4;
    import where net_dev_4();
    export filter default_route_4;
  };
}

template bgp peer_dev_6 from peer_dev {
  ipv6 {
    table master6;
    import where net_dev_6();
    export filter default_route_6;
  };
}

protocol bgp peer_dev_kenny10_4 from peer_dev_4 {
  neighbor 172.20.6.9 as 64512;
}

protocol bgp peer_dev_kenny04_4 from peer_dev_4 {
  neighbor 172.20.6.10 as 64512;
}

protocol bgp peer_dev_kenny10_6 from peer_dev_6 {
  neighbor 2a06:3a80:0:ff::3 as 64512;
}

protocol bgp peer_dev_kenny04_6 from peer_dev_6 {
  neighbor 2a06:3a80:0:ff::2 as 64512;
}
